using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace GeneratedClasses
{
    /// <summary>
    /// Request/response body class for the PetStore /pet endpoint.
    /// Generated by API2Test from the OpenAPI schema.
    /// </summary>
    public class Pet
    {
        [JsonPropertyName("id")]
        public long Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; } = string.Empty;

        [JsonPropertyName("category")]
        public Category? Category { get; set; }

        [JsonPropertyName("photoUrls")]
        public List<string> PhotoUrls { get; set; } = new();

        [JsonPropertyName("tags")]
        public List<Tag> Tags { get; set; } = new();

        [JsonPropertyName("status")]
        public string Status { get; set; } = string.Empty;

        public string ToJson() => JsonSerializer.Serialize(this);

        public static Pet? FromJson(string json) =>
            JsonSerializer.Deserialize<Pet>(json);
    }

    public class Category
    {
        [JsonPropertyName("id")]
        public long Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; } = string.Empty;
    }

    public class Tag
    {
        [JsonPropertyName("id")]
        public long Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; } = string.Empty;
    }
}
